from app.models import db
from mixins import BaseMixin

class EltOrdDeal(BaseMixin, db.Model):
    __tablename__ = 'ord_deal'

    id = db.Column(db.Integer, primary_key=True, server_default=db.text("nextval('ord_deal_id_seq'::regclass)"))
    client_account_id = db.Column(db.Integer, nullable=False)
    ord_id = db.Column(db.Integer)
    deal_id = db.Column(db.Integer)
    client_code = db.Column(db.String(10), nullable=False)
    title_desc = db.Column(db.String(70))
    client_firstname_lc = db.Column(db.String(150))
    client_lastname_lc = db.Column(db.String(150))
    client_firstname_en = db.Column(db.String(150))
    client_lastname_en = db.Column(db.String(150))
    fullname_lc = db.column_property(client_firstname_lc + " " + client_lastname_lc)

    market = db.Column(db.String(1))
    broker_no = db.Column(db.String(4))
    sb_no = db.Column(db.String(4))
    sb_order_no = db.Column(db.String(64))
    branch_code = db.Column(db.String(6))
    order_no = db.Column(db.String(64), nullable=False)
    x_order_no = db.Column(db.String(64))
    x_match_no = db.Column(db.String(64))
    confirm_no = db.Column(db.String(64))
    securities_id = db.Column(db.Integer, nullable=False)
    sec_symbol = db.Column(db.String(20), nullable=False)
    trustee_id = db.Column(db.String(2))
    side = db.Column(db.String(1), nullable=False)
    board = db.Column(db.String(1))
    price = db.Column(db.Numeric(16, 6))
    condition_price = db.Column(db.String(3))
    matched_price = db.Column(db.Numeric(16, 6))
    qty = db.Column(db.Numeric(20, 6), nullable=False)
    confirm_qty = db.Column(db.Numeric(20, 6))
    order_status = db.Column(db.String(1))
    condition = db.Column(db.String(1))
    order_type = db.Column(db.String(1))
    special_order_type = db.Column(db.String(1))
    basket_no = db.Column(db.String(10))
    pc_flag = db.Column(db.String(1), nullable=False)
    pt_type = db.Column(db.String(1), server_default=db.text("'0'::character varying"))
    sbl_type = db.Column(db.String(1))
    order_date = db.Column(db.Date, nullable=False)
    order_date_time = db.Column(db.DateTime, nullable=False)
    cancel_date_time = db.Column(db.DateTime)
    change_date_time = db.Column(db.DateTime)
    deal_date = db.Column(db.Date)
    deal_time = db.Column(db.DateTime)
    ae_code = db.Column(db.String(64))
    front_user_code = db.Column(db.String(64))
    cancel_user_code = db.Column(db.String(64))
    approve_user_code = db.Column(db.String(64))
    set_trader_id = db.Column(db.String(64))
    channel_code = db.Column(db.String(3), nullable=False)
    front_trading_system = db.Column(db.String(2), nullable=False)
    itw_mode = db.Column(db.String(1))
    net_amount = db.Column(db.Numeric(16, 6))
    commission = db.Column(db.Numeric(16, 6))
    fee = db.Column(db.Numeric(16, 6))
    clearing_fee = db.Column(db.Numeric(16, 6))
    trading_fee = db.Column(db.Numeric(16, 6))
    settlement_fee = db.Column(db.Numeric(16, 6))
    vat = db.Column(db.Numeric(16, 6))
    withholding_tax = db.Column(db.Numeric(16, 6))
    manual_commission_flag = db.Column(db.Boolean)

